version: 2

models:
  - name: dim_listings
    description: Dimension table which contains Airbnb listings.
    columns:
    
      - name: listing_id
        description: Primary key for the listing table.
        tests:
          - unique
          - not_null

      - name: host_id
        description: The hosts's id. References the host table.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts')
              field: host_id

      - name: room_type
        description: Type of the apartment/room
        tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']

      - name: minimum_nights
        description: '{{ doc("dim_listing_minimum_nights") }}'
        tests:
          - positive_value


  - name: dim_hosts
    description: Dimension table which contains Airbnb hosts.
    columns:
    
      - name: host_id
        description: Primary key for the host table.
        tests:
          - unique
          - not_null
      
      - name: host_name
        description: The name of the host
        tests:
          - not_null
      
      - name: is_superhost
        description: Defines whether the hosts is a superhost.
        tests:
          - accepted_values:
              values: ['t', 'f']


  - name: dim_listings_with_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')



  # - name: fact_reviews
  #   description: Fact table which contains all the transactions of Airbnb.
  #   columns:
  #     - name: listing_id
  #       tests:
  #         - relationships:
  #           to: ref('dim_listings')
  #           field: listing_id
      
  #     - name: reviewer_name
  #       tests:
  #        - not_null
      
  #     - name: review_sentiment
  #       tests:
  #         - accepted_values:
  #             values: ['positive', 'neutral', 'negative']

      